import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginRight: 16,
    width: 280,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  wideCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  header: {
    flexDirection: "row",
    marginBottom: 8,
  },
  image: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
  },
  info: {
    flex: 1,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#333",
  },
  teacher: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  due: {
    fontSize: 12,
    color: "#999",
  },
  materialToggle: {
    backgroundColor: "#f5f5f5",
    padding: 12,
    borderRadius: 8,
    marginVertical: 8,
  },
  materialToggleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  materialToggleText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333"
  },
  arrowIcon: {
    marginRight: 8,
  },
  listContainer: {
    marginVertical: 8,
    paddingLeft: 8,
  },
  listItem: {
    fontSize: 14,
    marginBottom: 4,
    color: "#333",
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 8,
    color: "#333",
  },
  deleteButton: {
    backgroundColor: "#ff4d4f",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 16,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  link: {
    color: "#1890ff",
    marginVertical: 8,
  },
  addButton: {
    backgroundColor: "#1890ff",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginVertical: 8,
  },
  taskCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
  },
  taskDescription: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  taskDeadline: {
    fontSize: 12,
    color: "#999",
    marginBottom: 8,
  },
  taskDelete: {
    color: "#ff4d4f",
    fontSize: 14,
    marginTop: 8,
    textAlign: "right",
  },
  assignmentCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  assignmentTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
  },
  assignmentDescription: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  assignmentDeadline: {
    fontSize: 12,
    color: "#999",
    marginBottom: 8,
  },
  assignmentDelete: {
    color: "#ff4d4f",
    fontSize: 14,
    marginTop: 8,
    textAlign: "right",
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 20,
    width: "80%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 4,
    padding: 10,
    marginBottom: 16,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalButton: {
    padding: 10,
    borderRadius: 4,
    flex: 1,
    marginHorizontal: 5,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  favoriteButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 20,
    padding: 5,
    zIndex: 10,
  },
  emptyFavoritesContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  emptyFavoritesText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    marginTop: 10,
  },
  emptyFavoritesIcon: {
    marginBottom: 10,
  },
  filterContainer: {
    flexDirection: "row",
    padding: 10,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    marginBottom: 10,
    alignItems: "center",
  },
  filterInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 4,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    color: "#333",
  },
  filterIcon: {
    marginRight: 10,
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 10,
  },
  paginationButton: {
    padding: 10,
    backgroundColor: "#1890ff",
    borderRadius: 4,
    marginHorizontal: 5,
  },
  paginationButtonDisabled: {
    padding: 10,
    backgroundColor: "#ccc",
    borderRadius: 4,
    marginHorizontal: 5,
  },
  paginationText: {
    color: "#fff",
  },
  paginationInfo: {
    marginHorizontal: 10,
  },
})
